/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.vistas;

import interfaces.IControladorPrincipal;
import javax.swing.JFrame;

public class VentanaPrincipal extends JFrame {
    private IControladorPrincipal controlador;

    /**
     * Constructor
     * @param controlador controlador de la ventana
     */
    public VentanaPrincipal(IControladorPrincipal controlador) {
        initComponents();
        this.controlador = controlador;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPalabrasClaves = new javax.swing.JButton();
        btnLugares = new javax.swing.JButton();
        btnIdiomas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnTipos = new javax.swing.JButton();
        btnPublicaciones = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repositorios");
        setResizable(false);

        btnPalabrasClaves.setMnemonic('P');
        btnPalabrasClaves.setText("Palabras Claves");
        btnPalabrasClaves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPalabrasClaves.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPalabrasClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalabrasClavesClic(evt);
            }
        });

        btnLugares.setMnemonic('L');
        btnLugares.setText("Lugares");
        btnLugares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLugares.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugaresClic(evt);
            }
        });

        btnIdiomas.setMnemonic('I');
        btnIdiomas.setText("Idiomas");
        btnIdiomas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIdiomas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomasClic(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auxiliares/Salir.jpg"))); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirClic(evt);
            }
        });

        btnTipos.setMnemonic('T');
        btnTipos.setText("Tipos");
        btnTipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTipos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposClic(evt);
            }
        });

        btnPublicaciones.setMnemonic('U');
        btnPublicaciones.setText("Publicaciones");
        btnPublicaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPublicaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicacionesClic(evt);
            }
        });

        btnAutores.setMnemonic('A');
        btnAutores.setText("Autores");
        btnAutores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAutores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresClic(evt);
            }
        });

        btnGrupos.setMnemonic('G');
        btnGrupos.setText("Grupos");
        btnGrupos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrupos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposClic(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPalabrasClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPalabrasClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAutores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirClic
        this.controlador.btnSalirClic(evt);
    }//GEN-LAST:event_btnSalirClic

    private void btnLugaresClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugaresClic
        this.controlador.btnLugaresClic(evt);
    }//GEN-LAST:event_btnLugaresClic

    private void btnIdiomasClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomasClic
        this.controlador.btnIdiomasClic(evt);
    }//GEN-LAST:event_btnIdiomasClic

    private void btnPalabrasClavesClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalabrasClavesClic
        this.controlador.btnPalabrasClavesClic(evt);
    }//GEN-LAST:event_btnPalabrasClavesClic

    private void btnTiposClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposClic
        this.controlador.btnTiposClic(evt);
    }//GEN-LAST:event_btnTiposClic

    private void btnPublicacionesClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicacionesClic
        this.controlador.btnPublicacionesClic(evt);
    }//GEN-LAST:event_btnPublicacionesClic

    private void btnAutoresClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresClic
        this.controlador.btnAutoresClic(evt);
    }//GEN-LAST:event_btnAutoresClic

    private void btnGruposClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposClic
        this.controlador.btnGruposClic(evt);
    }//GEN-LAST:event_btnGruposClic


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnIdiomas;
    private javax.swing.JButton btnLugares;
    private javax.swing.JButton btnPalabrasClaves;
    private javax.swing.JButton btnPublicaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTipos;
    // End of variables declaration//GEN-END:variables
}
